import type { Metadata } from "next";
import { ApolloWrapper } from "@/lib/apollo.client";
import Providers from "@/state/Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pokémon Explorer",
  description: "Generated by create next app",
  icons: {
    icon: "/pokemon-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/pokemon-icon.png" />
      </head>
      <body className="min-h-dvh bg-neutral-950 text-neutral-100">
        <div className="mx-auto max-w-3xl p-4">
          <h1
            className="text-3xl font-bold mb-4 
             bg-gradient-to-r from-purple-500 via-pink-700
             bg-clip-text text-transparent font-sans"
          >
            Pokémon Explorer
          </h1>
          <Providers>
            <ApolloWrapper>{children}</ApolloWrapper>
          </Providers>
        </div>
      </body>
    </html>
  );
}
